language: python

python:
    - 3.3
    - 3.4

env:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=0

before_install:
    - sudo apt-get install gearman-job-server

install:
    - pip install flake8
    - pip install nose
    - pip install coverage
    - pip install .
    - pip install coveralls

script:
    - make cov

after_success:
    - coveralls
